version: 0.2

env:
  variables:
    REPOSITORY_NAME: applysample-staging

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Repository URI is $REPOSITORY_URI"
      - echo "Image tag is $IMAGE_TAG"
  build:
    commands:
      - echo "Building Docker image..."
      - cd ApplySample/src/ApplySample
      - docker build --quiet -t $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo "Pushing Docker images..."
      - docker push --quiet $REPOSITORY_URI:latest
      - docker push --quiet $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creating deployment artifact..."
      - cd $CODEBUILD_SRC_DIR
      - printf '[{"name":"ApplySampleContainer","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json